config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
    resources :comments
  end

  root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :commenter_name, :comment_body, presence: true
  validates :commenter_name, length: { minimum: 2, maximum: 20 }
  validates :comment_body, exclusion: { in: %w(boring), message: "Please do not use negative language!"}
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    @comment = @post.comments
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new    
  end

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.create(comment_params)
    if comment.save
      redirect_to post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    post = Post.find(params[:post_id])
    comment = post.comments.find(params[:id])
    comment.update(comment_params)
    if comment.save
      redirect_to post_comments_path
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    post.comments.find(params[:id]).destroy

    redirect_to "@post"    
  end

  protected
  def comment_params
    params.require(:comment).permit(:commenter_name, :comment_body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    new_post = Post.create(post_params)
    new_post.save

    redirect_to new_post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)

    redirect_to post
  end

  def destroy
    @post = Post.destroy(params[:id])
    redirect_to @post
  end

  protected
  def post_params
    params.require(:post).permit(:username, :title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_controller_helper.rb
module CommentControllerHelper
end

app/helpers/post_controller_helper.rb
module PostControllerHelper
end

app/views/comments/_comment.html.erb
<p>
<h4><%= comment.comment_body %></h4>
  Commenter: <%= comment.commenter_name %>
<br>
<%= link_to "Show", post_comment_path(@post, comment) %> |
<%= link_to "Edit", edit_post_comment_path(@post, comment) %> |

  <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete %>
</p>

app/views/comments/_form.html.erb
 <% if @comment.errors.any? %>
  <h3> <%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved.</h3>

  <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>



<%= form_for([@post,@comment]) do |f| %>

  <%= f.label :commenter_name %>
  <%= f.text_field :commenter_name %>

  <%= f.label :comment_body %>
  <%= f.text_field :comment_body%>

  <%= f.submit %>

<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form" %>

app/views/comments/index.html.erb
<h3>Comments: </h3>

<%= render @post.comments %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render "form" %>

app/views/comments/show.html.erb
<h1>Comment Show Page</h1>

<%= render @comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlogSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>

<% end %>

app/views/posts/_post.html.erb
<h1><%= post.title %> </h1>
<h3>By: <%= post.username %></h3>
<p>Body: <%= post.body %> </p>

<%= link_to "Show Page", post if action_name == "index" %> | 
<%= link_to "Edit Post", edit_post_path(post) %> |
<%= link_to "Delete", post, method: :delete, data: { confirm: "Are you sure?" } %>
<br>
--------------------------------------

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<%= link_to "Add New Post", new_post_path(@post) %>

<%= render @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

 <%= render "form" %>

app/views/posts/show.html.erb
<h1>Post Show Page</h1>

<%= render @post %>
<br>


  <h2>Comments: </h2>
  <%= render @post.comments %>

<br>

<%= link_to "Add New Comment", new_post_comment_path(@post) %>